[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"

[scrolling]
history = 100000


[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Medium"
size = 14

[terminal]
shell = "/opt/homebrew/bin/fish"

[cursor.style]
blinking = "Always"
